build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - mvn clean install -Djacoco.skip=true -Dmaven.test.skip=true
    
test-job:
  stage: test
  script:
    - echo "Run controller and service tests"
    - mvn test

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
